---------------------------------------
-- ATTENZIONE BISOGNA SELEZIONARE IL PATH CORRETTO DA METTERE NEI DATAFILES ALTRIMENTI SCOPPIA TUTTO
---------------------------------------

--SELECT * FROM DBA_DATA_FILES WHERE TABLESPACE_NAME = 'USERS';
---------------------------------------
---------------------------------------

-- BEGIN
-- EXECUTE IMMEDIATE 'DROP USER QINETIC_BNPL CASCADE';
-- EXCEPTION WHEN OTHERS THEN NULL;
-- END;
-- /
--
-- BEGIN
-- EXECUTE IMMEDIATE 'DROP TABLESPACE QINETIC_BNPL INCLUDING CONTENTS AND DATAFILES';
-- EXCEPTION WHEN OTHERS THEN NULL;
-- END;
-- /

create tablespace QINETIC_BNPL
    datafile '/u01/app/oracle/oradata/xe/QINETIC_BNPL.dbf'
    size 10m
    autoextend on
    logging
    online
    force logging
    extent management local
    segment space management auto;


CREATE USER QINETIC_BNPL IDENTIFIED BY QINETIC_BNPL;

ALTER USER QINETIC_BNPL
    DEFAULT TABLESPACE QINETIC_BNPL
    TEMPORARY TABLESPACE TEMP
    ACCOUNT UNLOCK;

ALTER USER QINETIC_BNPL QUOTA UNLIMITED ON QINETIC_BNPL;

GRANT CONNECT TO QINETIC_BNPL;
GRANT RESOURCE TO QINETIC_BNPL;

ALTER USER QINETIC_BNPL DEFAULT ROLE CONNECT,RESOURCE;

GRANT CREATE VIEW TO QINETIC_BNPL;
GRANT CREATE SESSION TO QINETIC_BNPL;
GRANT CREATE TABLE TO QINETIC_BNPL;
GRANT CREATE SYNONYM TO QINETIC_BNPL;
GRANT CREATE ANY VIEW TO QINETIC_BNPL;