---------------------------------------
-- ATTENZIONE BISOGNA SELEZIONARE IL PATH CORRETTO DA METTERE NEI DATAFILES ALTRIMENTI SCOPPIA TUTTO
---------------------------------------

--SELECT * FROM DBA_DATA_FILES WHERE TABLESPACE_NAME = 'USERS';
---------------------------------------
---------------------------------------

-- BEGIN
-- EXECUTE IMMEDIATE 'DROP USER QINETIC_ROUTER CASCADE';
-- EXCEPTION WHEN OTHERS THEN NULL;
-- END;
-- /
--
-- BEGIN
-- EXECUTE IMMEDIATE 'DROP TABLESPACE QINETIC_ROUTER INCLUDING CONTENTS AND DATAFILES';
-- EXCEPTION WHEN OTHERS THEN NULL;
-- END;
-- /

create tablespace QINETIC_ROUTER
    datafile '/u01/app/oracle/oradata/xe/QINETIC_ROUTER.dbf'
    size 10m
    autoextend on
    logging
    online
    force logging
    extent management local
    segment space management auto;


CREATE USER QINETIC_ROUTER IDENTIFIED BY QINETIC_ROUTER;

ALTER USER QINETIC_ROUTER
    DEFAULT TABLESPACE QINETIC_ROUTER
    TEMPORARY TABLESPACE TEMP
    ACCOUNT UNLOCK;

ALTER USER QINETIC_ROUTER QUOTA UNLIMITED ON QINETIC_ROUTER;

GRANT CONNECT TO QINETIC_ROUTER;
GRANT RESOURCE TO QINETIC_ROUTER;

ALTER USER QINETIC_ROUTER DEFAULT ROLE CONNECT,RESOURCE;

GRANT CREATE VIEW TO QINETIC_ROUTER;
GRANT CREATE SESSION TO QINETIC_ROUTER;
GRANT CREATE TABLE TO QINETIC_ROUTER;
GRANT CREATE SYNONYM TO QINETIC_ROUTER;
GRANT CREATE ANY VIEW TO QINETIC_ROUTER;